language: go
go:
 - 1.7.5
 - 1.8
 - tip
env:
 - BUILD_GOOS=darwin
 - BUILD_GOOS=linux

script:
 - GOOS=$BUILD_GOOS go build -o keysync cmd/keysync/keysync.go
 - GOOS=$BUILD_GOOS go build -o keyrestore cmd/keyrestore/keyrestore.go
 - go test -v .
