---
secrets_directory: './testing/secrets'
client_directory: './testing/clients'
ca_file: './testing/cacert.crt'
yaml_ext: yaml
chown_files: false
server: 'localhost:4444'
debug: true
default_user: 'keysync-test'
default_group: 'keysync-test'
passwd_file: '/etc/passwd'
group_file: '/etc/group'
api_port: 31738
poll_interval: 1s
